name: Linux Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
          architecture: x64

      - name: Install Ninja     
        run: |
           sudo apt-get update -y
           sudo apt-get install -y ninja-build libgtk-3-dev keybinder-3.0
      
      - name: enable linux support for flutter
        run: flutter config --enable-linux-desktop
      
      - name: Get dependencies
        run: |
         flutter pub get
         ls -la

      # Runs a set of commands using the runners shell
      - name: Start release build
        run: |
         flutter build linux
         ls -la build/linux/x64/release