name: Linux Release

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter the tag of this release'
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
    steps:
    
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
          architecture: x64

      - name: Install required tools     
        run: |
           sudo apt-get update -y
           sudo apt-get install -y ninja-build libgtk-3-dev keybinder-3.0
      
      - name: Enable linux-desktop for flutter
        run: flutter config --enable-linux-desktop
      
      - name: Get dependencies
        run: flutter pub get

      - name: Start the build process
        run: flutter build linux
         
      - name: Compress 
        run: tar -cvJf Brisk-${{ inputs.tag }}-linux-x86_64.tar.xz -C build/linux/x64/release/bundle/ .

      - name: Upload artifact 
        uses: actions/upload-artifact@v4.0.0
        with:
          name: brisk
          path: ./Brisk-${{ inputs.tag }}-linux-x86_64.tar.xz

  Release:
    runs-on: ubuntu-latest
    needs: Build
    permissions:
      contents: write
    steps:
    
      - name: Donwload artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: brisk

      - name: Release the changes
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag }} 
          body: Test version!
          files: ./Brisk-${{ inputs.tag }}-linux-x86_64.tar.xz

  Cleanup:
    needs:
      - Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
      - name: Remove build artifacts
        uses: geekyeggo/delete-artifact@v1
      
 
