name: Linux Release Test

on:
  workflow_dispatch:



jobs:
  version:
    runs-on: windows-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4.1.5

      - name: Extract Version from pubspec.yaml
        id: extract_version
        run: |
          $VERSION = Select-String  -Path ".\pubspec.yaml" -Pattern "version: (\d+\.\d+\.\d+)" -CaseSensitive | ForEach-Object{ $_.Matches.Groups[1].Value }
          echo version=$VERSION >> $env:GITHUB_OUTPUT

  Build-package:
    runs-on: macos-latest
    permissions:
      contents: read
    needs: version
    steps:

      - name: Checkout the code
        uses: actions/checkout@v4.1.5

      - name: Install flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: "3.22.0"
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'

      - name: Enable linux-desktop for flutter
        run: flutter config --enable-macos-desktop && export PATH="$PATH":"$HOME/.pub-cache/bin"

      - name: Get dependencies
        run: flutter pub get

      - name: Start the build process
        run: flutter build macos

      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Start the build process
        run: flutter_distributor package --platform macos --targets dmg

      - name: debug
        run: ls dist/macos/
