name: Release All Platforms

on:
  workflow_dispatch:

jobs:
  version:
    uses: ./.github/workflows/version.yml

  Build-windows:
   uses: ./.github/workflows/windows.yml
   with:
      version: ${{ needs.version.outputs.version }}
   needs: version

  Build-linux:
   uses: ./.github/workflows/linux.yml
   with:
      version: ${{ needs.version.outputs.version }}
   needs: version

  Release:
    runs-on: ubuntu-latest
    needs: [Build-linux, Build-windows, version]
    permissions:
      contents: write
    steps:

      - name: Checkout the code
        uses: actions/checkout@v4.1.5

      - name: Download linux artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: brisk-linux

      - name: Download windows package
        uses: actions/download-artifact@v4.1.0
        with:
          name: brisk-windows

      - name: Release the changes
        uses: softprops/action-gh-release@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.version.outputs.version }}
          body_path: ./.github/release.md
          files: |
            ./Brisk-v${{ needs.version.outputs.version }}-linux-x86_64.rpm
            ./Brisk-v${{ needs.version.outputs.version }}-linux-x86_64.deb
            ./Brisk-v${{ needs.version.outputs.version }}-linux-x86_64.tar.xz
            ./Brisk-v${{ needs.version.outputs.version }}-windows-x86_64.zip
            ./Brisk-v${{ needs.version.outputs.version }}-windows-x86_64.exe
